/*
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

// C interface for the statically linked KlyLogger library.

#pragma once

#ifndef KLY_LOGGER_C_INCLUDED
#define KLY_LOGGER_C_INCLUDED

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <limits.h>
#include <wchar.h>

#ifdef __cplusplus
extern "C" {
#endif

// Opaque logger handle. Its C++ implementation is private to KlyLogger.cpp.
typedef struct _KlyLoggerHandle * KlyLoggerHandle;

// Code to execute before a log message has been output.
typedef void (*KlyLoggerBeforeLogCallback)();
// Code to execute after a log message has been output. The callback receives the original message and the plain-text message with formatting removed.
typedef void (*KlyLoggerAfterLogCallback)(const wchar_t *original_message, const wchar_t *plain_message);

// Type information retained internally for C arguments passed to fmt.
typedef enum KlyLoggerFormatArgType {
	KLY_LOGGER_FORMAT_SIGNED_INTEGER,
	KLY_LOGGER_FORMAT_UNSIGNED_INTEGER,
	KLY_LOGGER_FORMAT_FLOATING_POINT,
	KLY_LOGGER_FORMAT_LONG_DOUBLE,
	KLY_LOGGER_FORMAT_BOOLEAN,
	KLY_LOGGER_FORMAT_CHARACTER,
	KLY_LOGGER_FORMAT_WIDE_CHARACTER,
	KLY_LOGGER_FORMAT_STRING,
	KLY_LOGGER_FORMAT_WIDE_STRING,
	KLY_LOGGER_FORMAT_POINTER
} KlyLoggerFormatArgType;

// One tagged formatting argument. Normal calls create these values
// automatically; the explicit type remains available for advanced use.
// String and pointer values are borrowed only for the duration of the call.
typedef struct KlyLoggerFormatArg {
	KlyLoggerFormatArgType type;
	union {
		int64_t signed_integer;
		uint64_t unsigned_integer;
		double floating_point;
		long double long_double_value;
		bool boolean;
		char character;
		wchar_t wide_character;
		const char *string;
		const wchar_t *wide_string;
		const void *pointer;
	} value;
} KlyLoggerFormatArg;

static inline KlyLoggerFormatArg kly_logger_arg_signed(int64_t value) {
	KlyLoggerFormatArg result = { KLY_LOGGER_FORMAT_SIGNED_INTEGER };
	result.value.signed_integer = value;
	return result;
}

static inline KlyLoggerFormatArg kly_logger_arg_unsigned(uint64_t value) {
	KlyLoggerFormatArg result = { KLY_LOGGER_FORMAT_UNSIGNED_INTEGER };
	result.value.unsigned_integer = value;
	return result;
}

static inline KlyLoggerFormatArg kly_logger_arg_double(double value) {
	KlyLoggerFormatArg result = { KLY_LOGGER_FORMAT_FLOATING_POINT };
	result.value.floating_point = value;
	return result;
}

static inline KlyLoggerFormatArg kly_logger_arg_long_double(long double value) {
	KlyLoggerFormatArg result = { KLY_LOGGER_FORMAT_LONG_DOUBLE };
	result.value.long_double_value = value;
	return result;
}

static inline KlyLoggerFormatArg kly_logger_arg_bool(bool value) {
	KlyLoggerFormatArg result = { KLY_LOGGER_FORMAT_BOOLEAN };
	result.value.boolean = value;
	return result;
}

static inline KlyLoggerFormatArg kly_logger_arg_char(char value) {
	KlyLoggerFormatArg result = { KLY_LOGGER_FORMAT_CHARACTER };
	result.value.character = value;
	return result;
}

static inline KlyLoggerFormatArg kly_logger_arg_wchar(wchar_t value) {
	KlyLoggerFormatArg result = { KLY_LOGGER_FORMAT_WIDE_CHARACTER };
	result.value.wide_character = value;
	return result;
}

static inline KlyLoggerFormatArg kly_logger_arg_string(const char *value) {
	KlyLoggerFormatArg result = { KLY_LOGGER_FORMAT_STRING };
	result.value.string = value;
	return result;
}

static inline KlyLoggerFormatArg kly_logger_arg_wstring(const wchar_t *value) {
	KlyLoggerFormatArg result = { KLY_LOGGER_FORMAT_WIDE_STRING };
	result.value.wide_string = value;
	return result;
}

static inline KlyLoggerFormatArg kly_logger_arg_pointer(const void *value) {
	KlyLoggerFormatArg result = { KLY_LOGGER_FORMAT_POINTER };
	result.value.pointer = value;
	return result;
}

static inline KlyLoggerFormatArg kly_logger_arg_identity(const KlyLoggerFormatArg value) { return value; }

#define KLY_INT_ARG(value) kly_logger_arg_signed((int64_t)(value))
#define KLY_UINT_ARG(value) kly_logger_arg_unsigned((uint64_t)(value))
#define KLY_DOUBLE_ARG(value) kly_logger_arg_double((double)(value))
#define KLY_LONG_DOUBLE_ARG(value) kly_logger_arg_long_double((long double)(value))
#define KLY_BOOL_ARG(value) kly_logger_arg_bool((bool)(value))
#define KLY_CHAR_ARG(value) kly_logger_arg_char((char)(value))
#define KLY_WCHAR_ARG(value) kly_logger_arg_wchar((wchar_t)(value))
#define KLY_STRING_ARG(value) kly_logger_arg_string((value))
#define KLY_WSTRING_ARG(value) kly_logger_arg_wstring((value))
#define KLY_POINTER_ARG(value) kly_logger_arg_pointer((const void *)(value))

#ifndef __cplusplus
// C11 type selector used automatically by the logging convenience macros.
// Explicit KLY_*_ARG macros remain available when exact control is required.
// Some C implementations typedef wchar_t to char. In that case char * and
// wchar_t * are compatible types and cannot both appear in one _Generic list.
// KlyLogger is wide-string-first, so wchar_t remains the automatic default;
// pass narrow strings through KLY_STRING_ARG explicitly on such platforms.
#if WCHAR_MAX > UCHAR_MAX
#define KLY_LOGGER_DETAIL_NARROW_STRING_ASSOCIATIONS \
	char *: kly_logger_arg_string, \
	const char *: kly_logger_arg_string,
#else
#define KLY_LOGGER_DETAIL_NARROW_STRING_ASSOCIATIONS
#endif

#define KLY_ARG(value) _Generic((value), \
	KlyLoggerFormatArg: kly_logger_arg_identity, \
	_Bool: kly_logger_arg_bool, \
	char: kly_logger_arg_char, \
	signed char: kly_logger_arg_signed, \
	unsigned char: kly_logger_arg_unsigned, \
	short: kly_logger_arg_signed, \
	unsigned short: kly_logger_arg_unsigned, \
	int: kly_logger_arg_signed, \
	unsigned int: kly_logger_arg_unsigned, \
	long: kly_logger_arg_signed, \
	unsigned long: kly_logger_arg_unsigned, \
	long long: kly_logger_arg_signed, \
	unsigned long long: kly_logger_arg_unsigned, \
	float: kly_logger_arg_double, \
	double: kly_logger_arg_double, \
	long double: kly_logger_arg_long_double, \
	KLY_LOGGER_DETAIL_NARROW_STRING_ASSOCIATIONS \
	wchar_t *: kly_logger_arg_wstring, \
	const wchar_t *: kly_logger_arg_wstring, \
	default: kly_logger_arg_pointer \
)(value)
#endif

// Construct a logger with no name.
KlyLoggerHandle kly_logger_create();
// Construct a logger with a wide string name.
KlyLoggerHandle kly_logger_create_named(const wchar_t *name);
// Construct a logger with a narrow string name.
KlyLoggerHandle kly_logger_create_named_narrow(const char *name);

// Retrieve the logger description as a narrow string. The returned pointer is owned by the logger and remains valid until that logger is destroyed.
const char *kly_logger_string(const KlyLoggerHandle logger);
// Retrieve the logger description as a wide string. The returned pointer is owned by the logger and remains valid until that logger is destroyed.
const wchar_t *kly_logger_wstring(const KlyLoggerHandle logger);

// Log wide-string messages at the four supported levels.
void kly_logger_info(KlyLoggerHandle logger, const wchar_t *message);
void kly_logger_warn(KlyLoggerHandle logger, const wchar_t *message);
void kly_logger_error(KlyLoggerHandle logger, const wchar_t *message);
void kly_logger_fatal(KlyLoggerHandle logger, const wchar_t *message);

// Internal bridges used by the C11 convenience macros below. Applications should call kly_logger_info/warn/error/fatal instead.
void kly_logger_detail_info_args(KlyLoggerHandle logger, const wchar_t *format, const KlyLoggerFormatArg *arguments, size_t argument_count);
void kly_logger_detail_warn_args(KlyLoggerHandle logger, const wchar_t *format, const KlyLoggerFormatArg *arguments, size_t argument_count);
void kly_logger_detail_error_args(KlyLoggerHandle logger, const wchar_t *format, const KlyLoggerFormatArg *arguments, size_t argument_count);
void kly_logger_detail_fatal_args(KlyLoggerHandle logger, const wchar_t *format, const KlyLoggerFormatArg *arguments, size_t argument_count);

// Log narrow-string messages at the four supported levels.
void kly_logger_info_narrow(KlyLoggerHandle logger, const char *message);
void kly_logger_warn_narrow(KlyLoggerHandle logger, const char *message);
void kly_logger_error_narrow(KlyLoggerHandle logger, const char *message);
void kly_logger_fatal_narrow(KlyLoggerHandle logger, const char *message);

// Internal narrow-string bridges used by the convenience macros.
void kly_logger_detail_info_narrow_args(KlyLoggerHandle logger, const char *format, const KlyLoggerFormatArg *arguments, size_t argument_count);
void kly_logger_detail_warn_narrow_args(KlyLoggerHandle logger, const char *format, const KlyLoggerFormatArg *arguments, size_t argument_count);
void kly_logger_detail_error_narrow_args(KlyLoggerHandle logger, const char *format, const KlyLoggerFormatArg *arguments, size_t argument_count);
void kly_logger_detail_fatal_narrow_args(KlyLoggerHandle logger, const char *format, const KlyLoggerFormatArg *arguments, size_t argument_count);

// Check whether all pending log tasks have been processed.
bool kly_logger_finished_tasks();
// Block the current thread until all log output is complete.
void kly_logger_wait();
// Register callbacks that run before or after each output line. Pass NULL to clear the corresponding callback.
void kly_logger_set_before_log(KlyLoggerBeforeLogCallback callback);
void kly_logger_set_after_log(KlyLoggerAfterLogCallback callback);

#ifdef __cplusplus
}
#else
typedef KlyLoggerHandle KlyLogger;

// C cannot recover argument types from a raw va_list: unlike printf's %d/%ls,
// a {} field does not encode a type. These C11 macros provide the same call
// shape while using _Generic to preserve each type and deriving the count at
// compile time. Up to 16 formatting arguments are accepted per call.
#define KLY_LOGGER_DETAIL_CAT_RAW(left, right) left##right
#define KLY_LOGGER_DETAIL_CAT(left, right) KLY_LOGGER_DETAIL_CAT_RAW(left, right)
#define KLY_LOGGER_DETAIL_COUNT_RAW( \
	_1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, count, ...) count
#define KLY_LOGGER_DETAIL_COUNT(...) KLY_LOGGER_DETAIL_COUNT_RAW(__VA_ARGS__, \
	18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0)

#define KLY_LOGGER_DETAIL_MAP_1(a1) KLY_ARG(a1)
#define KLY_LOGGER_DETAIL_MAP_2(a1, a2) KLY_ARG(a1), KLY_LOGGER_DETAIL_MAP_1(a2)
#define KLY_LOGGER_DETAIL_MAP_3(a1, a2, a3) KLY_ARG(a1), KLY_LOGGER_DETAIL_MAP_2(a2, a3)
#define KLY_LOGGER_DETAIL_MAP_4(a1, a2, a3, a4) KLY_ARG(a1), KLY_LOGGER_DETAIL_MAP_3(a2, a3, a4)
#define KLY_LOGGER_DETAIL_MAP_5(a1, a2, a3, a4, a5) KLY_ARG(a1), KLY_LOGGER_DETAIL_MAP_4(a2, a3, a4, a5)
#define KLY_LOGGER_DETAIL_MAP_6(a1, a2, a3, a4, a5, a6) KLY_ARG(a1), KLY_LOGGER_DETAIL_MAP_5(a2, a3, a4, a5, a6)
#define KLY_LOGGER_DETAIL_MAP_7(a1, a2, a3, a4, a5, a6, a7) KLY_ARG(a1), KLY_LOGGER_DETAIL_MAP_6(a2, a3, a4, a5, a6, a7)
#define KLY_LOGGER_DETAIL_MAP_8(a1, a2, a3, a4, a5, a6, a7, a8) KLY_ARG(a1), KLY_LOGGER_DETAIL_MAP_7(a2, a3, a4, a5, a6, a7, a8)
#define KLY_LOGGER_DETAIL_MAP_9(a1, a2, a3, a4, a5, a6, a7, a8, a9) KLY_ARG(a1), KLY_LOGGER_DETAIL_MAP_8(a2, a3, a4, a5, a6, a7, a8, a9)
#define KLY_LOGGER_DETAIL_MAP_10(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10) KLY_ARG(a1), KLY_LOGGER_DETAIL_MAP_9(a2, a3, a4, a5, a6, a7, a8, a9, a10)
#define KLY_LOGGER_DETAIL_MAP_11(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11) KLY_ARG(a1), KLY_LOGGER_DETAIL_MAP_10(a2, a3, a4, a5, a6, a7, a8, a9, a10, a11)
#define KLY_LOGGER_DETAIL_MAP_12(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12) KLY_ARG(a1), KLY_LOGGER_DETAIL_MAP_11(a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12)
#define KLY_LOGGER_DETAIL_MAP_13(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13) KLY_ARG(a1), KLY_LOGGER_DETAIL_MAP_12(a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13)
#define KLY_LOGGER_DETAIL_MAP_14(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14) KLY_ARG(a1), KLY_LOGGER_DETAIL_MAP_13(a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14)
#define KLY_LOGGER_DETAIL_MAP_15(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15) KLY_ARG(a1), KLY_LOGGER_DETAIL_MAP_14(a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15)
#define KLY_LOGGER_DETAIL_MAP_16(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16) KLY_ARG(a1), KLY_LOGGER_DETAIL_MAP_15(a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16)
#define KLY_LOGGER_DETAIL_MAP(count, ...) KLY_LOGGER_DETAIL_CAT(KLY_LOGGER_DETAIL_MAP_, count)(__VA_ARGS__)

#define KLY_LOGGER_DETAIL_FORMAT(format_function, logger, format, count, ...) \
	(format_function)((logger), (format), \
		(const KlyLoggerFormatArg[]){KLY_LOGGER_DETAIL_MAP(count, __VA_ARGS__)}, (size_t)(count))
#define KLY_LOGGER_DETAIL_CALL_2(message_function, format_function, logger, message) \
	(message_function)((logger), (message))
#define KLY_LOGGER_DETAIL_CALL_3(message_function, format_function, logger, format, ...) KLY_LOGGER_DETAIL_FORMAT(format_function, logger, format, 1, __VA_ARGS__)
#define KLY_LOGGER_DETAIL_CALL_4(message_function, format_function, logger, format, ...) KLY_LOGGER_DETAIL_FORMAT(format_function, logger, format, 2, __VA_ARGS__)
#define KLY_LOGGER_DETAIL_CALL_5(message_function, format_function, logger, format, ...) KLY_LOGGER_DETAIL_FORMAT(format_function, logger, format, 3, __VA_ARGS__)
#define KLY_LOGGER_DETAIL_CALL_6(message_function, format_function, logger, format, ...) KLY_LOGGER_DETAIL_FORMAT(format_function, logger, format, 4, __VA_ARGS__)
#define KLY_LOGGER_DETAIL_CALL_7(message_function, format_function, logger, format, ...) KLY_LOGGER_DETAIL_FORMAT(format_function, logger, format, 5, __VA_ARGS__)
#define KLY_LOGGER_DETAIL_CALL_8(message_function, format_function, logger, format, ...) KLY_LOGGER_DETAIL_FORMAT(format_function, logger, format, 6, __VA_ARGS__)
#define KLY_LOGGER_DETAIL_CALL_9(message_function, format_function, logger, format, ...) KLY_LOGGER_DETAIL_FORMAT(format_function, logger, format, 7, __VA_ARGS__)
#define KLY_LOGGER_DETAIL_CALL_10(message_function, format_function, logger, format, ...) KLY_LOGGER_DETAIL_FORMAT(format_function, logger, format, 8, __VA_ARGS__)
#define KLY_LOGGER_DETAIL_CALL_11(message_function, format_function, logger, format, ...) KLY_LOGGER_DETAIL_FORMAT(format_function, logger, format, 9, __VA_ARGS__)
#define KLY_LOGGER_DETAIL_CALL_12(message_function, format_function, logger, format, ...) KLY_LOGGER_DETAIL_FORMAT(format_function, logger, format, 10, __VA_ARGS__)
#define KLY_LOGGER_DETAIL_CALL_13(message_function, format_function, logger, format, ...) KLY_LOGGER_DETAIL_FORMAT(format_function, logger, format, 11, __VA_ARGS__)
#define KLY_LOGGER_DETAIL_CALL_14(message_function, format_function, logger, format, ...) KLY_LOGGER_DETAIL_FORMAT(format_function, logger, format, 12, __VA_ARGS__)
#define KLY_LOGGER_DETAIL_CALL_15(message_function, format_function, logger, format, ...) KLY_LOGGER_DETAIL_FORMAT(format_function, logger, format, 13, __VA_ARGS__)
#define KLY_LOGGER_DETAIL_CALL_16(message_function, format_function, logger, format, ...) KLY_LOGGER_DETAIL_FORMAT(format_function, logger, format, 14, __VA_ARGS__)
#define KLY_LOGGER_DETAIL_CALL_17(message_function, format_function, logger, format, ...) KLY_LOGGER_DETAIL_FORMAT(format_function, logger, format, 15, __VA_ARGS__)
#define KLY_LOGGER_DETAIL_CALL_18(message_function, format_function, logger, format, ...) KLY_LOGGER_DETAIL_FORMAT(format_function, logger, format, 16, __VA_ARGS__)

#define KLY_LOGGER_DETAIL_DISPATCH_RAW(count, ...) KLY_LOGGER_DETAIL_CAT(KLY_LOGGER_DETAIL_CALL_, count)(__VA_ARGS__)
#define KLY_LOGGER_DETAIL_DISPATCH(message_function, format_function, ...) \
	KLY_LOGGER_DETAIL_DISPATCH_RAW(KLY_LOGGER_DETAIL_COUNT(__VA_ARGS__), message_function, format_function, __VA_ARGS__)

#define kly_logger_info(...) KLY_LOGGER_DETAIL_DISPATCH(kly_logger_info, kly_logger_detail_info_args, __VA_ARGS__)
#define kly_logger_warn(...) KLY_LOGGER_DETAIL_DISPATCH(kly_logger_warn, kly_logger_detail_warn_args, __VA_ARGS__)
#define kly_logger_error(...) KLY_LOGGER_DETAIL_DISPATCH(kly_logger_error, kly_logger_detail_error_args, __VA_ARGS__)
#define kly_logger_fatal(...) KLY_LOGGER_DETAIL_DISPATCH(kly_logger_fatal, kly_logger_detail_fatal_args, __VA_ARGS__)
#define kly_logger_info_narrow(...) KLY_LOGGER_DETAIL_DISPATCH(kly_logger_info_narrow, kly_logger_detail_info_narrow_args, __VA_ARGS__)
#define kly_logger_warn_narrow(...) KLY_LOGGER_DETAIL_DISPATCH(kly_logger_warn_narrow, kly_logger_detail_warn_narrow_args, __VA_ARGS__)
#define kly_logger_error_narrow(...) KLY_LOGGER_DETAIL_DISPATCH(kly_logger_error_narrow, kly_logger_detail_error_narrow_args, __VA_ARGS__)
#define kly_logger_fatal_narrow(...) KLY_LOGGER_DETAIL_DISPATCH(kly_logger_fatal_narrow, kly_logger_detail_fatal_narrow_args, __VA_ARGS__)
#endif

#endif
