/*
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#pragma once

#ifndef KLY_LOGGER_INCLUDED
#define KLY_LOGGER_INCLUDED

#include <exception>
#include <functional>
#include <locale>
#include <memory>
#include <string>
#include <tuple>
#include <type_traits>
#include <utility>

#include <fmt/format.h>
#include <fmt/xchar.h>

// Type traits for string conversion.
template<typename T, typename = void>
struct has_string : std::false_type {};

template<typename T>
struct has_string<T, std::void_t<decltype(std::declval<T>().string())>> : std::true_type {};

template<typename T, typename = void>
struct has_wstring : std::false_type {};

template<typename T>
struct has_wstring<T, std::void_t<decltype(std::declval<T>().wstring())>> : std::true_type {};

// KlyLogger: A lightweight, color console and file logging library for C++.
class KlyLogger {
public:
	// LogStyle encapsulates all visual and textual attributes for a log level, including level name, Windows console colors, and ANSI escape sequences.
	struct LogStyle {
		std::string level, levelAnsiColor, textAnsiColor;
		uint16_t levelColor, textColor;
	};

	static const LogStyle INFO_STYLE, WARN_STYLE, ERROR_STYLE, FATAL_STYLE;

	// String conversion utilities.
	class StringConverter {
	public:
		// Convert wide string to narrow string.
		static std::string toString(const std::wstring &str);

		// Convert narrow string to wide string safely.
		static std::wstring toWString(const std::string &str);

		// Decode UTF-8 with the Windows conversion API.
#ifdef _WIN32
		static std::wstring win32_toWString(const std::string &str);
#endif

		// Convert formatting inputs into values or references without shared temporary storage.
		template<typename T>
		static decltype(auto) convertFormattingValue(const T &arg) {
			if constexpr (std::is_same_v<T, std::string> || std::is_convertible_v<T, const char *>) return toWString(arg);
			else if constexpr (has_wstring<T>::value) return std::wstring(arg.wstring());
			else if constexpr (has_string<T>::value) return toWString(arg.string());
			else return (arg);
		}

		// Convert any argument into std::wstring for formatting. Returns the original value if already wide string, otherwise uses fmt::format.
		template<typename T>
		static std::wstring convertArgumentToWString(const T &arg) {
			// If already a std::wstring or convertible to const wchar_t*, return directly.
			if constexpr (std::is_same_v<T, std::wstring> || std::is_convertible_v<T, const wchar_t *>) return std::wstring(arg);
			// Otherwise, format the argument into a wide string using fmt::format.
			else return fmt::format(L"{}", arg);
		}

		// Format a message with optional arguments, returning the formatted wide string.
		template<typename MessageType, typename... Args>
		static std::wstring formatMessage(const MessageType &message, const Args &...args) {
			// Convert message to wide string format.
			const auto convertedMessage = convertFormattingValue(message);
			const std::wstring msg = convertArgumentToWString(convertedMessage);
			std::wstring formatted = msg;

			// Format message with arguments if provided.
			if constexpr (sizeof...(args) > 0) {
				try {
					// Keep converted arguments alive for the complete formatting call.
					std::tuple<decltype(convertFormattingValue(args))...> convertedArguments{ convertFormattingValue(args)... };
					formatted = std::apply([&msg](const auto &...converted) {
						return fmt::vformat(fmt::wstring_view(msg), fmt::make_wformat_args(converted...));
					}, convertedArguments);
				} catch (const std::exception &e) {
					// Append error message if formatting fails.
					formatted = msg + L"\xa78\xa7o (" + toWString(e.what()) + L')';
				}
			}

			return formatted;
		}
	};

private:
	// Logger name as wide string.
	std::wstring name{};

	// Logger descriptions cached for the public reference-returning accessors.
	std::wstring as_wstring{};
	std::string as_string{};

	// Code to execute before and after this logger's output, copied into each submitted log task.
	using BeforeLogCallback = std::function<void()>;
	using AfterLogCallback = std::function<void(const std::wstring &, const std::wstring &)>;
	mutable std::shared_ptr<const BeforeLogCallback> beforeLog;
	mutable std::shared_ptr<const AfterLogCallback> afterLog;

	void submitLog(std::wstring message, const LogStyle &style) const;

	// Submit a log output task to the logging thread.
	template<typename MessageType, typename... Args>
	void log(const MessageType &message, const LogStyle &style, const Args &...args) const {
		submitLog(StringConverter::formatMessage(message, args...), style);
	}

public:
	// Construct a logger with no name.
	KlyLogger();

	// Construct a logger with a std::wstring name.
	KlyLogger(const std::wstring &name);

	// Construct a logger with a std::string name.
	KlyLogger(const std::string &name);

	// Copy callbacks while synchronized with callback registration.
	KlyLogger(const KlyLogger &logger);

	// Move callbacks while synchronized with callback registration.
	KlyLogger(KlyLogger &&logger) noexcept;

	// Retrieve logger name as std::string.
	[[nodiscard]] const std::string &string() const noexcept;

	// Retrieve logger name as std::wstring.
	[[nodiscard]] const std::wstring &wstring() const noexcept;

	// Log an INFO-level message.
	template<typename MessageType, typename... Args>
	void info(const MessageType &message, const Args &...args) const {
		log(message, INFO_STYLE, args...);
	}

	// Log an WARN-level message.
	template<typename MessageType, typename... Args>
	void warn(const MessageType &message, const Args &...args) const {
		log(message, WARN_STYLE, args...);
	}

	// Log an ERROR-level message.
	template<typename MessageType, typename... Args>
	void error(const MessageType &message, const Args &...args) const {
		log(message, ERROR_STYLE, args...);
	}

	// Log an FATAL-level message.
	template<typename MessageType, typename... Args>
	void fatal(const MessageType &message, const Args &...args) const {
		log(message, FATAL_STYLE, args...);
	}

	// Check if all pending log tasks have been processed.
	static bool finishedTasks();

	// Block the current thread until all log output is completed.
	static void wait();

	// Register a callback function to execute after each log output from this logger.
	// The callback receives two parameters:
	//   1. The original log message (may include formatting codes).
	//   2. The plain text version of the message (with formatting removed).
	void setAfterLog(const std::function<void(const std::wstring &, const std::wstring &)> &func) const;

	// Register a callback function to execute before each log output from this logger.
	void setBeforeLog(const std::function<void()> &func) const;
};

#endif