/*
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#include "KlyLogger.hpp"
#include "KlyLogger.h"

#include <algorithm>
#include <atomic>
#include <condition_variable>
#include <cstdio>
#include <ctime>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <mutex>
#include <new>
#include <sys/stat.h>
#include <thread>
#include <unordered_map>

#include <fmt/args.h>

#ifdef _WIN32
#ifndef NOMINMAX
#define NOMINMAX
#endif
#include <Windows.h>
#include <io.h>
// The original header queried RtlGetVersion before enabling ANSI output. The
// split implementation probes console mode support directly, avoiding an
// RtlGetVersion declaration conflict and an ntdll.lib dependency.
#define KLY_ISATTY _isatty
#define KLY_FILENO _fileno
#else
#include <unistd.h>
#define KLY_ISATTY isatty
#define KLY_FILENO fileno
#endif

// Visual and textual attributes for each log level, including Windows console colors and ANSI escape sequences.
const KlyLogger::LogStyle KlyLogger::INFO_STYLE{"INFO", "\33[0;92m", "\33[0;37m", 10, 7};
const KlyLogger::LogStyle KlyLogger::WARN_STYLE{"WARN", "\33[0;33m", "\33[0;93m", 6, 14};
const KlyLogger::LogStyle KlyLogger::ERROR_STYLE{"ERROR", "\33[0;31m", "\33[0;91m", 4, 12};
const KlyLogger::LogStyle KlyLogger::FATAL_STYLE{"FATAL", "\33[2;31m", "\33[0;31m", 32772, 4};

// Log task containing logger name, log message, and log style.
struct LogTask {
	KlyLogger::LogStyle style;
	std::wstring name, message;
};

// Retrieve the current local time using the platform-safe conversion routine.
std::tm getLocalTime() {
	const std::time_t now = std::time(nullptr);
	std::tm result{};
#ifdef _WIN32
	localtime_s(&result, &now);
#else
	localtime_r(&now, &result);
#endif
	return result;
}

// Format a time structure as an HH:MM:SS string.
std::wstring formatTime(const std::tm &time) {
	return fmt::format(L"{:02}:{:02}:{:02} ", time.tm_hour, time.tm_min, time.tm_sec);
}

#ifndef KLY_LOGGER_OPTION_NO_LOG_FILE
// File logging helper.
class FileLogger {
public:
	// Initialize the file logging system if this library variant enables it.
	void initialize() { logFile_ = getLogFileHandle(); }

	// Update the log file handle when the local date changes.
	void updateIfNeeded() {
		if (packDate(getLocalTime()) != logFileCreateDate_) {
			if (logFile_.is_open()) logFile_.close();
			initialize();
		}
	}

	// Output a narrow string to the log file.
	void write(const std::string &message) {
		if (logFile_.is_open()) logFile_ << message;
	}

	// Convert and output a wide string to the log file.
	void write(const std::wstring &message) {
		if (logFile_.is_open()) logFile_ << KlyLogger::StringConverter::toString(message);
	}

	// Flush the completed line to the log file.
	void newline() {
		if (logFile_.is_open()) logFile_ << std::endl;
	}

private:
	// Pack date components into a compact unsigned integer representation.
	static unsigned packDate(const std::tm &time) {
		return (static_cast<unsigned>(time.tm_year) << 16) + (static_cast<unsigned>(time.tm_mon) << 8) + static_cast<unsigned>(time.tm_mday);
	}

	// Get the absolute path of the current executable.
	static std::filesystem::path getExecutablePath() {
#ifdef _WIN32
		// Get the executable path on Windows.
		std::wstring path(1024, L'\0');
		const DWORD length = GetModuleFileNameW(nullptr, path.data(), static_cast<DWORD>(path.size()));
		if (length == 0) return {};
		path.resize(length);
#else
		// Get the executable path on Linux.
		std::string path(1024, '\0');
		const ssize_t length = readlink("/proc/self/exe", path.data(), path.size() - 1);
		if (length == -1) return {};
		path.resize(static_cast<std::size_t>(length));
#endif
		return path;
	}

	// Retrieve the current log file handle, creating directories and rotating logs if needed.
	std::ofstream getLogFileHandle() {
		try {
			// Initialize the logs directory and latest log path if empty.
			if (logsDirectory_.empty() || latestLog_.empty()) {
				logsDirectory_ = getExecutablePath().parent_path() / "logs";
				latestLog_ = logsDirectory_ / "latest.log";
			}

			// Ensure the log directory exists.
			std::filesystem::create_directories(logsDirectory_);
			const std::tm time = getLocalTime();
			// Rename the existing latest.log before opening a new one.
			rotateLogFiles(time);
			logFileCreateDate_ = packDate(time);
			return std::ofstream(latestLog_, std::ios::out | std::ios::trunc | std::ios::binary);
		} catch (...) {
			// Disable file output if directory creation, rotation, or opening fails.
			return {};
		}
	}

	// Rename latest.log to a dated backup using YYYY-MM-DD-N.log.
	void rotateLogFiles(const std::tm &time) {
		if (!std::filesystem::exists(latestLog_)) return;

		std::tm fileTime{};
		struct stat fileStat {};
		if (stat(latestLog_.string().c_str(), &fileStat)) fileTime = time;
		else {
#ifdef _WIN32
			localtime_s(&fileTime, &fileStat.st_mtime);
#else
			localtime_r(&fileStat.st_mtime, &fileTime);
#endif
		}

		// Find the first available filename by incrementing its numeric suffix.
		unsigned index = 1;
		std::filesystem::path rotated;
		do {
			rotated = logsDirectory_ / fmt::format(L"{:04}-{:02}-{:02}-{}.log", fileTime.tm_year + 1900, fileTime.tm_mon + 1, fileTime.tm_mday, index++);
		} while (std::filesystem::exists(rotated));
		std::filesystem::rename(latestLog_, rotated);
	}

	// Date on which the active log file was created.
	unsigned logFileCreateDate_{};
	// Active log file handle, log directory, and latest.log path.
	std::ofstream logFile_;
	std::filesystem::path logsDirectory_;
	std::filesystem::path latestLog_;
};
#endif

// Platform-specific console handling.
class Console {
public:
	// Detect terminal output and initialize ANSI escape-sequence support.
	Console() : isAtty_(KLY_ISATTY(KLY_FILENO(stderr)) != 0), ansiSupported_(initializeAnsi()) {}

	// Set the text color for current console output.
	void setColor(uint16_t color, const std::string &ansi) {
		if (!isAtty_) return;
		if (ansiSupported_) lineBuffer_ += KlyLogger::StringConverter::toWString(ansi.begin(), ansi.end());
#ifdef _WIN32
		else SetConsoleTextAttribute(getHandle(), color);
#endif
	}

	// Output a narrow string to the console and log file.
	void write(const std::string &message) {
		if (isAtty_) {
			if (ansiSupported_) lineBuffer_ += KlyLogger::StringConverter::toWString(message.begin(), message.end());
#ifdef _WIN32
			else WriteConsoleA(getHandle(), message.c_str(), static_cast<DWORD>(message.length()), nullptr, nullptr);
#endif
		}
#ifndef KLY_LOGGER_OPTION_NO_LOG_FILE
		fileLogger_.write(message);
#endif
	}

	// Output a wide string to the console and log file.
	void write(const std::wstring &message) {
		if (isAtty_) {
			if (ansiSupported_) lineBuffer_ += message;
#ifdef _WIN32
			else WriteConsoleW(getHandle(), message.c_str(), static_cast<DWORD>(message.length()), nullptr, nullptr);
#endif
		}
#ifndef KLY_LOGGER_OPTION_NO_LOG_FILE
		fileLogger_.write(message);
#endif
	}

	// Flush buffered line content to the console and log file.
	void flushLine() {
#ifdef _WIN32
		if (isAtty_) {
			if (ansiSupported_) {
				lineBuffer_.push_back(L'\n');
				WriteConsoleW(getHandle(), lineBuffer_.c_str(), static_cast<DWORD>(lineBuffer_.length()), nullptr, nullptr);
			} else WriteConsoleA(getHandle(), "\n", 1, nullptr, nullptr);
		}
#else
		if (isAtty_) std::cerr << KlyLogger::StringConverter::toString(lineBuffer_) << std::endl;
#endif
#ifndef KLY_LOGGER_OPTION_NO_LOG_FILE
		fileLogger_.newline();
#endif
		lineBuffer_.clear();
	}

	// Clear remaining content in the current console line.
	void clearLine() {
		if (!isAtty_) return;
		if (ansiSupported_) lineBuffer_ += L"\33[m\33[K";
#ifdef _WIN32
		else {
			// On Windows without ANSI, fill the rest of the line with spaces and reset its text attributes.
			SetConsoleTextAttribute(getHandle(), 7);
			CONSOLE_SCREEN_BUFFER_INFO info{};
			if (GetConsoleScreenBufferInfo(getHandle(), &info)) {
				DWORD length = static_cast<DWORD>(info.dwSize.X - info.dwCursorPosition.X);
				FillConsoleOutputCharacterA(getHandle(), ' ', length, info.dwCursorPosition, &length);
				FillConsoleOutputAttribute(getHandle(), info.wAttributes, length, info.dwCursorPosition, &length);
			}
		}
#endif
	}

	// Process Minecraft color codes in message text and optionally return a plain-text copy with those formatting codes removed.
	std::wstring processColorCodes(std::wstring message,
		uint16_t initialColor,
		const std::string &ansiColor,
		bool stripMessage) {
		std::wstring stripped;
		while (!message.empty() && message.back() == L'\247') message.pop_back();

		std::size_t position;
		while ((position = message.find(L'\247')) != std::wstring::npos) {
			const std::wstring part = message.substr(0, position);
			write(part);
			if (stripMessage) stripped += part;
			if (isAtty_ && position + 1 < message.length()) applyMinecraftColorCode(message[position + 1], initialColor, ansiColor);
			message = message.substr(position + 2);
		}

		if (!message.empty()) {
			write(message);
			if (stripMessage) stripped += message;
		}
		return stripped;
	}


#ifndef KLY_LOGGER_OPTION_NO_LOG_FILE
	// Forward file lifecycle operations to the file logging helper.
	void updateLogFile() { fileLogger_.updateIfNeeded(); }
	void initializeLogFile() { fileLogger_.initialize(); }
#endif

	bool isAtty() const { return isAtty_; }

private:
	// Initialize the console and check whether ANSI escape sequences are supported. If output is not a terminal, ANSI output stays disabled.
	bool initializeAnsi() {
		if (!isAtty_) return false;
#ifdef _WIN32
		// Enable virtual terminal processing so the console recognizes ANSI escape sequences.
		// If console mode cannot be read or changed, assume ANSI is unsupported and use the legacy color API.
		DWORD mode = 0;
		return GetConsoleMode(getHandle(), &mode) && SetConsoleMode(getHandle(), mode | ENABLE_VIRTUAL_TERMINAL_PROCESSING);
#else
		return true;
#endif
	}

	// Get the text attributes of the current console text.
	uint16_t getTextAttribute() const {
#ifdef _WIN32
		CONSOLE_SCREEN_BUFFER_INFO info{};
		return GetConsoleScreenBufferInfo(getHandle(), &info) ? info.wAttributes : 7;
#else
		return 0;
#endif
	}

	// Set console text color and style from a Minecraft-style color code.
	void applyMinecraftColorCode(wchar_t code, uint16_t initialColor, const std::string &ansiColor) {
		// Lookup table converting Minecraft colors to ANSI sequences.
		static constexpr const char *colors[]{
			"\33[30m", "\33[0;34m", "\33[0;32m", "\33[0;36m", "\33[0;31m", "\33[0;35m", "\33[0;33m", "\33[0;37m",
			"\33[0;90m", "\33[0;94m", "\33[0;92m", "\33[0;96m", "\33[0;91m", "\33[0;95m", "\33[0;93m", "\33[0;97m"};

		// Numeric and alphabetic color codes only change the text color.
		if (L'0' <= code && code <= L'9') {
			setColor(static_cast<uint16_t>(code - L'0'), colors[code - L'0']);
			return;
		}
		if (L'a' <= code && code <= L'f') {
			setColor(static_cast<uint16_t>(code - L'W'), colors[code - L'W']);
			return;
		}

		// Formatting codes use mappings based on the active text attributes, reset restores the level's initial color.
		const uint16_t attribute = getTextAttribute();
		std::unordered_map<wchar_t, std::pair<uint16_t, std::string>> mappings{
			{ L'k', { static_cast<uint16_t>(attribute | 0x4000), "\33[5m" } },
			{ L'l', { attribute, "\33[21m" } },
			{ L'm', { attribute, "\33[9m" } },
			{ L'n', { static_cast<uint16_t>(attribute | 0x8000), "\33[4m" } },
			{ L'o', { attribute, "\33[3m" } },
			{ L'r', { initialColor, ansiColor } } };
		const auto found = mappings.find(code);
		if (found != mappings.end()) setColor(found->second.first, found->second.second);
	}

#ifdef _WIN32
	// Get the Windows stderr handle with optional caching.
	static HANDLE getHandle() {
#ifndef KLY_LOGGER_OPTION_NO_CACHE_FOR_OUTPUT_HANDLE
		// In cache mode, retrieve the stderr handle only once.
		static const HANDLE handle = GetStdHandle(STD_ERROR_HANDLE);
		return handle;
#else
		// In no-cache mode, retrieve the stderr handle for each output.
		return GetStdHandle(STD_ERROR_HANDLE);
#endif
	}
#endif

	// Terminal and ANSI capability flags.
	bool isAtty_;
	bool ansiSupported_;
	// Cache complete ANSI lines to reduce console output frequency.
	std::wstring lineBuffer_;
#ifndef KLY_LOGGER_OPTION_NO_LOG_FILE
	FileLogger fileLogger_;
#endif
};

// Thread-safe runtime that owns the log queue, callbacks, and background logging thread. A mutex and condition variables replace the old spin lock.
class Runtime {
public:
	// Initialize the background thread that processes queued log tasks.
	Runtime() : worker_([this] { run(); }) {}

	// Wait for queued output, request worker shutdown, and join the thread.
	~Runtime() {
		wait();
		{
			std::lock_guard lock(mutex_);
			stopping_ = true;
		}
		workAvailable_.notify_one();
		worker_.join();
	}

	// Submit a log output task to the logging thread.
	void submit(const LogTask &task) {
		{
			std::lock_guard lock(mutex_);
			queue_.push(task);
		}
		workAvailable_.notify_one();
	}

	// Check whether queued and currently processing tasks are complete.
	bool finished() const {
		std::lock_guard lock(mutex_);
		return queue_.empty() && !processing_;
	}

	// Block the current thread until all log output is completed.
	void wait() {
		std::unique_lock lock(mutex_);
		finished_.wait(lock, [this] { return queue_.empty() && !processing_; });
	}

	// Register code to execute before each log message is output.
	void setBefore(std::function<void()> callback) {
		std::lock_guard lock(mutex_);
		beforeLog_ = std::move(callback);
	}

	// Register code to execute after each log message is output.
	void setAfter(std::function<void(const std::wstring &, const std::wstring &)> callback) {
		std::lock_guard lock(mutex_);
		afterLog_ = std::move(callback);
	}

private:
	// Process log tasks until runtime shutdown.
	void run() {
#ifdef _WIN32
		// Set the logging thread to the lowest priority.
		SetThreadPriority(GetCurrentThread(), THREAD_PRIORITY_IDLE);
#endif
#ifndef KLY_LOGGER_OPTION_NO_LOG_FILE
		console_.initializeLogFile();
#endif

		// Keep the worker alive until process shutdown, sleeping while the queue is empty instead of busy-waiting.
		while (true) {
			LogTask task;
			std::function<void()> before;
			std::function<void(const std::wstring &, const std::wstring &)> after;
			{
				std::unique_lock lock(mutex_);
				workAvailable_.wait(lock, [this] { return stopping_ || !queue_.empty(); });
				if (stopping_ && queue_.empty()) return;
				task = std::move(queue_.front());
				queue_.pop();
				processing_ = true;
				before = beforeLog_;
				after = afterLog_;
			}

			processMessage(task, before, after);

			{
				std::lock_guard lock(mutex_);
				processing_ = false;
				if (queue_.empty()) finished_.notify_all();
			}
		}
	}

	// Process a complete log message, including line splitting.
	void processMessage(const LogTask &task,
		const std::function<void()> &before,
		const std::function<void(const std::wstring &, const std::wstring &)> &after) {
		std::wstring message = task.message;
		std::size_t newlinePosition;
		while ((newlinePosition = findNextNewline(message)) != std::wstring::npos) {
			processSingleLine(task.name, message.substr(0, newlinePosition), task.style, before, after);
			message = message.substr(newlinePosition + 1);
		}
		if (!message.empty()) processSingleLine(task.name, message, task.style, before, after);
	}

	// Find the position of the next CR or LF newline character.
	static std::size_t findNextNewline(const std::wstring &message) {
		const std::size_t carriageReturn = message.find(L'\r');
		const std::size_t lineFeed = message.find(L'\n');
		if (carriageReturn == std::wstring::npos) return lineFeed;
		if (lineFeed == std::wstring::npos) return carriageReturn;
		return std::min(carriageReturn, lineFeed);
	}

	// Process one non-empty log line with callbacks and formatting.
	void processSingleLine(const std::wstring &name,
		const std::wstring &message,
		const KlyLogger::LogStyle &style,
		const std::function<void()> &before,
		const std::function<void(const std::wstring &, const std::wstring &)> &after) {
		if (message.empty()) return;
		if (before) {
			try {
				before();
			} catch (...) {}
		}
#ifndef KLY_LOGGER_OPTION_NO_LOG_FILE
		console_.updateLogFile();
#endif
		printTimestamp(name, style);
		const std::wstring stripped = console_.processColorCodes(message, style.textColor, style.textAnsiColor, static_cast<bool>(after));
		if (after) {
			try {
				after(message, stripped);
			} catch (...) {}
		}
		console_.clearLine();
		console_.flushLine();
	}

	// Print the current time, level, and optional logger name.
	void printTimestamp(const std::wstring &name, const KlyLogger::LogStyle &style) {
		// Set cyan for the timestamp bracket when output is a terminal.
		if (console_.isAtty()) console_.setColor(3, "\33[0;36m");
		console_.write("\r[");
		console_.setColor(3, "\33[0;36m");
		// Write formatted local time (HH:MM:SS).
		console_.write(formatTime(getLocalTime()));
		// Set the level-specific color and write the level text.
		console_.setColor(style.levelColor, style.levelAnsiColor);
		console_.write(style.level);
		// Reset to cyan for the closing bracket.
		console_.setColor(3, "\33[0;36m");
		console_.write("] ");
		// Add the logger name section when a name was supplied.
		if (!name.empty()) {
			console_.write("[");
			// Process color codes embedded in the logger name.
			console_.processColorCodes(name, 3, "\33[0;36m", false);
			console_.setColor(3, "\33[0;36m");
			console_.write("] ");
		}
		// Set the final color for the actual log message.
		console_.setColor(style.textColor, style.textAnsiColor);
	}

	// Queue lock and worker wake/completion signals.
	mutable std::mutex mutex_;
	std::condition_variable workAvailable_;
	std::condition_variable finished_;
	// Log task queue processed by the background thread.
	std::queue<LogTask> queue_;
	// Code to execute before and after a log message has been output.
	std::function<void()> beforeLog_;
	std::function<void(const std::wstring &, const std::wstring &)> afterLog_;
	// Worker state used by finished() and orderly shutdown.
	bool processing_{};
	bool stopping_{};
	// Console/file output backend and its worker thread.
	Console console_;
	std::thread worker_;
};

// Lazily create one process-wide logging runtime.
Runtime &runtime() {
	static Runtime instance;
	return instance;
}

// Normalize a logger name by discarding text before its final CR/LF.
std::wstring legalizeLoggerName(const std::wstring &loggerName) {
	const std::size_t lastPosition = std::max(loggerName.find_last_of(L'\r'), loggerName.find_last_of(L'\n'));
	return lastPosition == std::wstring::npos ? loggerName : loggerName.substr(lastPosition + 1);
}

std::string KlyLogger::StringConverter::toString(const std::wstring &str) {
	return converter.to_bytes(str);
}

std::wstring KlyLogger::StringConverter::toWString(const std::string &str) {
#ifdef _WIN32
	// On Windows, try the active system code page first. MB_ERR_INVALID_CHARS ensures invalid character sequences cause conversion failure.
	if (!str.empty()) {
		// Query the required output length before allocating the wide string.
		const int length = MultiByteToWideChar(CP_ACP, MB_ERR_INVALID_CHARS, str.data(), static_cast<int>(str.size()), nullptr, 0);
		if (length > 0) {
			// Convert the narrow string with the exact required allocation.
			std::wstring result(static_cast<std::size_t>(length), L'\0');
			MultiByteToWideChar(CP_ACP, MB_ERR_INVALID_CHARS, str.data(), static_cast<int>(str.size()), result.data(), length);
			// Return the successfully converted wide string.
			return result;
		}
	}
#endif
	try {
		// Fallback: interpret the narrow string as UTF-8.
		return converter.from_bytes(str);
	} catch (const std::exception &error) {
		// If decoding fails, preserve the original bytes and append an error message instead of discarding the log content.
		const char *what = error.what();
		return toWString(str.begin(), str.end()) + L"\u00a78\u00a7o (decoder error: " + toWString(what, what + std::strlen(what)) + L')';
	}
}

void KlyLogger::StringConverter::clearConverted() {
	converted = std::queue<std::wstring>();
}

// Construct a logger with no name.
KlyLogger::KlyLogger() noexcept : as_wstring(L"KlyLogger{name=<empty>}"), as_string("KlyLogger{name=<empty>}") {}

// Construct a logger with a wide string name.
KlyLogger::KlyLogger(const std::wstring &loggerName) noexcept : name(::legalizeLoggerName(loggerName))
	, as_wstring(L"KlyLogger{name=" + (name.empty() ? L"<empty>" : name) + L'}'), as_string(StringConverter::toString(as_wstring)) {}

// Construct a logger with a narrow string name.
KlyLogger::KlyLogger(const std::string &loggerName) noexcept : name(::legalizeLoggerName(StringConverter::toWString(loggerName)))
	, as_wstring(L"KlyLogger{name=" + (loggerName.empty() ? L"<empty>" : name) + L'}'), as_string(StringConverter::toString(as_wstring)) {}

const std::string &KlyLogger::string() const noexcept { return as_string; }
const std::wstring &KlyLogger::wstring() const noexcept { return as_wstring; }

// Push a formatted log task to the background queue.
void KlyLogger::submitLog(const std::wstring &loggerName, std::wstring message, const KlyLogger::LogStyle &style) {
	runtime().submit({ style, loggerName, std::move(message) });
}

bool KlyLogger::finishedTasks() noexcept { return runtime().finished(); }
void KlyLogger::wait() noexcept { runtime().wait(); }

void KlyLogger::setAfterLog(const std::function<void(const std::wstring &, const std::wstring &)> &func) noexcept {
	runtime().setAfter(func);
}

void KlyLogger::setBeforeLog(const std::function<void()> &func) noexcept {
	runtime().setBefore(func);
}

// Convert the tagged C argument array into fmt's runtime argument store, then format the complete string in one pass.
// This preserves fmt's full parser, including positional arguments and nested dynamic width/precision fields.
std::wstring formatCMessage(const std::wstring &format,
	const KlyLoggerFormatArg *arguments,
	std::size_t argumentCount) {
	try {
		if (!arguments && argumentCount != 0) throw fmt::format_error("Format arguments are null");
		fmt::dynamic_format_arg_store<fmt::wformat_context> store;
		for (std::size_t index = 0; index < argumentCount; ++index) {
			const KlyLoggerFormatArg &argument = arguments[index];
			switch (argument.type) {
			case KLY_LOGGER_FORMAT_SIGNED_INTEGER:
				store.push_back(argument.value.signed_integer);
				break;
			case KLY_LOGGER_FORMAT_UNSIGNED_INTEGER:
				store.push_back(argument.value.unsigned_integer);
				break;
			case KLY_LOGGER_FORMAT_FLOATING_POINT:
				store.push_back(argument.value.floating_point);
				break;
			case KLY_LOGGER_FORMAT_LONG_DOUBLE:
				store.push_back(argument.value.long_double_value);
				break;
			case KLY_LOGGER_FORMAT_BOOLEAN:
				store.push_back(argument.value.boolean);
				break;
			case KLY_LOGGER_FORMAT_CHARACTER:
				store.push_back(static_cast<wchar_t>(static_cast<unsigned char>(argument.value.character)));
				break;
			case KLY_LOGGER_FORMAT_WIDE_CHARACTER:
				store.push_back(argument.value.wide_character);
				break;
			case KLY_LOGGER_FORMAT_STRING:
				store.push_back(argument.value.string ? KlyLogger::StringConverter::toWString(argument.value.string) : std::wstring());
				break;
			case KLY_LOGGER_FORMAT_WIDE_STRING:
				store.push_back(std::wstring(argument.value.wide_string ? argument.value.wide_string : L""));
				break;
			case KLY_LOGGER_FORMAT_POINTER:
				store.push_back(argument.value.pointer);
				break;
			default:
				throw fmt::format_error("Unknown KlyLoggerFormatArg type");
			}
		}
		return fmt::vformat(fmt::wstring_view(format), store);
	} catch (const std::exception &error) {
		return format + L"\u00a78\u00a7o (" + KlyLogger::StringConverter::toWString(error.what()) + L')';
	}
}

enum class CLogLevel { info, warn, error, fatal };

void logCFormatted(KlyLogger &logger,
	CLogLevel level,
	const std::wstring &format,
	const KlyLoggerFormatArg *arguments,
	std::size_t argumentCount) {
	const std::wstring message = formatCMessage(format, arguments, argumentCount);
	switch (level) {
		case CLogLevel::info:
			logger.info(message);
			break;
		case CLogLevel::warn:
			logger.warn(message);
			break;
		case CLogLevel::error:
			logger.error(message);
			break;
		case CLogLevel::fatal:
			logger.fatal(message);
			break;
	}
}

// Private C-handle representation that owns the public C++ logger object.
struct _KlyLoggerHandle {
	KlyLogger logger;
};

// C linkage wrappers preserve the C++ logger behavior behind an opaque handle.
extern "C" {

KlyLoggerHandle kly_logger_create() {
	try {
		return new _KlyLoggerHandle{ {} };
	} catch (...) {
		return nullptr;
	}
}

KlyLoggerHandle kly_logger_create_named(const wchar_t *name) {
	try {
		return new _KlyLoggerHandle{ std::wstring(name ? name : L"") };
	} catch (...) {
		return nullptr;
	}
}

KlyLoggerHandle kly_logger_create_named_narrow(const char *name) {
	try {
		return new _KlyLoggerHandle{ std::string(name ? name : "") };
	} catch (...) {
		return nullptr;
	}
}

const char *kly_logger_string(const KlyLoggerHandle logger) {
	return logger ? logger->logger.string().c_str() : nullptr;
}

const wchar_t *kly_logger_wstring(const KlyLoggerHandle logger) {
	return logger ? logger->logger.wstring().c_str() : nullptr;
}

void kly_logger_info(KlyLoggerHandle logger, const wchar_t *message) {
	if (logger) logger->logger.info(message ? message : L"");
}

void kly_logger_warn(KlyLoggerHandle logger, const wchar_t *message) {
	if (logger) logger->logger.warn(message ? message : L"");
}

void kly_logger_error(KlyLoggerHandle logger, const wchar_t *message) {
	if (logger) logger->logger.error(message ? message : L"");
}

void kly_logger_fatal(KlyLoggerHandle logger, const wchar_t *message) {
	if (logger) logger->logger.fatal(message ? message : L"");
}

void kly_logger_detail_info_args(KlyLoggerHandle logger, const wchar_t *format, const KlyLoggerFormatArg *arguments, size_t argumentCount) {
	if (logger) logCFormatted(logger->logger, CLogLevel::info, format ? format : L"", arguments, argumentCount);
}

void kly_logger_detail_warn_args(KlyLoggerHandle logger, const wchar_t *format, const KlyLoggerFormatArg *arguments, size_t argumentCount) {
	if (logger) logCFormatted(logger->logger, CLogLevel::warn, format ? format : L"", arguments, argumentCount);
}

void kly_logger_detail_error_args(KlyLoggerHandle logger, const wchar_t *format, const KlyLoggerFormatArg *arguments, size_t argumentCount) {
	if (logger) logCFormatted(logger->logger, CLogLevel::error, format ? format : L"", arguments, argumentCount);
}

void kly_logger_detail_fatal_args(KlyLoggerHandle logger, const wchar_t *format, const KlyLoggerFormatArg *arguments, size_t argumentCount) {
	if (logger) logCFormatted(logger->logger, CLogLevel::fatal, format ? format : L"", arguments, argumentCount);
}

void kly_logger_info_narrow(KlyLoggerHandle logger, const char *message) {
	if (logger) logger->logger.info(message ? message : "");
}

void kly_logger_warn_narrow(KlyLoggerHandle logger, const char *message) {
	if (logger) logger->logger.warn(message ? message : "");
}

void kly_logger_error_narrow(KlyLoggerHandle logger, const char *message) {
	if (logger) logger->logger.error(message ? message : "");
}

void kly_logger_fatal_narrow(KlyLoggerHandle logger, const char *message) {
	if (logger) logger->logger.fatal(message ? message : "");
}

void kly_logger_detail_info_narrow_args(KlyLoggerHandle logger, const char *format, const KlyLoggerFormatArg *arguments, size_t argumentCount) {
	if (logger) logCFormatted(logger->logger, CLogLevel::info, KlyLogger::StringConverter::toWString(format ? format : ""), arguments, argumentCount);
}

void kly_logger_detail_warn_narrow_args(KlyLoggerHandle logger, const char *format, const KlyLoggerFormatArg *arguments, size_t argumentCount) {
	if (logger) logCFormatted(logger->logger, CLogLevel::warn, KlyLogger::StringConverter::toWString(format ? format : ""), arguments, argumentCount);
}

void kly_logger_detail_error_narrow_args(KlyLoggerHandle logger, const char *format, const KlyLoggerFormatArg *arguments, size_t argumentCount) {
	if (logger) logCFormatted(logger->logger, CLogLevel::error, KlyLogger::StringConverter::toWString(format ? format : ""), arguments, argumentCount);
}

void kly_logger_detail_fatal_narrow_args(KlyLoggerHandle logger, const char *format, const KlyLoggerFormatArg *arguments, size_t argumentCount) {
	if (logger) logCFormatted(logger->logger, CLogLevel::fatal, KlyLogger::StringConverter::toWString(format ? format : ""), arguments, argumentCount);
}

bool kly_logger_finished_tasks() { return KlyLogger::finishedTasks(); }
void kly_logger_wait() { KlyLogger::wait(); }

void kly_logger_set_before_log(KlyLoggerBeforeLogCallback callback) {
	if (!callback) {
		KlyLogger::setBeforeLog({});
		return;
	}
	KlyLogger::setBeforeLog(callback);
}

void kly_logger_set_after_log(KlyLoggerAfterLogCallback callback) {
	if (!callback) {
		KlyLogger::setAfterLog({});
		return;
	}
	KlyLogger::setAfterLog([callback](const std::wstring &original, const std::wstring &plain) {
		callback(original.c_str(), plain.c_str());
	});
}

} // extern "C"
